export const COLORS = {
  BRAND_YELLOW: '#FEE500',
  CHAT_BG: '#B2C7D9',
  BUBBLE_RECEIVED: '#FFFFFF',
  BUBBLE_SENT: '#FEE500',
  BADGE_RED: '#FE4141',
  TEXT_PRIMARY: '#1A1A1A',
  TEXT_SECONDARY: '#888888',
  HEADER_BG: '#FFFFFF',
  DIVIDER: '#EBEBEB',
  SIDEBAR_BG: '#F9F9F9',
} as const
